spring.application.name=HealthSynqBackend

server.port=${PORT:8080}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

#spring.datasource.url=jdbc:postgresql://dpg-d6t8elshg0os73fl3gbg-a.oregon-postgres.render.com:5432/healthsynq?sslmode=require
#spring.datasource.username=healthsynq_user
#spring.datasource.password=ZF02xMB1E1CSnMdLRR7QhG4rWsaDfAzp

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

